### ISSUE TITLE
`remove` leaves `nil` instead of removing the element when dynamically generating a sequence

### ISSUE THREAD

**Issue by mateodif** [glojurelang/glojure#56]
It seems like the issue only occurs when dynamically generating a lazy seq using `map`, `for`, etc. I don't fully understand what's going on yet.

```clojure
user=> (defn gen-seq [x] (map vector (range x)))
#'user/gen-seq
user=> (gen-seq 2)
([0] [1])
user=> (remove #{[1]} (gen-seq 2))
([0] nil)
user=> (remove #{[1]} (lazy-seq [[0] [1]]))
([0])
user=> (remove #{[1]} (map (fn [n] [n]) (range 2)))
([0] nil)
user=> (= (lazy-seq [[0] [1]]) (map (fn [n] [n]) (range 2)))
true
```

**Comment by mateodif** [comment]
I think I know what's going on now.

To try and debug this, I've tinkered with the original [filter](https://github.com/clojure/clojure/blob/clojure-1.11.1/src/clj/clojure/core.clj#L2810) fn and made a simpler one that returns a chunk:
```clojure
(defn simple-filter [pred coll]
  (when-let [s (seq coll)]
    (let [c (chunk-first s)
          size (count c)
          b (chunk-buffer size)]
      (dotimes [i size]
          (let [v (.nth c i)]
            (when (pred v)
              (chunk-append b v))))
      (chunk b))))
```
In this version, I'm making it return a `chunk` to make it easier to see what the issue could be.
Basically, for a given coll of 5 elements, `filter` will create a chunk-buffer of size 5 and will then test the predicate and only append those that return a value.
In Glojure, we don't seem to filter out the `nil` values in a chunk:
```clojure
user=> (-> (chunk-buffer 32) (chunk) (chunk-cons (lazy-seq)))
(nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil)
```
While in Clojure's implementation, the same code gives us an empty seq:
```clojure
user=> (-> (chunk-buffer 32) (chunk) (chunk-cons (lazy-seq)))
()
```

So, in Glojure, if we filter out only the first element, we obtain a sequence of the original size of the chunk:
```clojure
user=> (filter #{1} (range 20))
(1 nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil)
```

I'm suspecting that the Clojure [chunkIterator](https://github.com/clojure/clojure/blob/08a2d9bdd013143a87e50fa82e9740e2ab4ee2c2/src/jvm/clojure/lang/RT.java#L516C7-L516C7) does some kind of filtering. I need to spend more time to think about it.

**Comment by jfhamlin** [comment]
Thanks for diving in here!
